name: 'add new pull request to project board'
description: 'Add a pull request to the first project on the repo'
branding:
  icon: 'git-pull-request'
  color: 'gray-dark'
inputs:
  github_token:
    description: 'GitHub token, use {{ secrets.GITHUB_TOKEN }}'
    required: true
  repository:
    description: 'repository path, use {{ github.repository }}'
    required: true
  pull_request:
    description: 'pull request number, use {{ github.event.pull_request.number }}'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
