name: 'Add to Project'
description: 'Add an issue to the first project on the repo'
inputs:
  issue:
    description: 'issue'
    required: true
  repository:
    description: 'repository'
    required: true
  github_token:
    description: 'github_token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
